defaultEntryPoints = ["http"]
logLevel = "INFO"
sendAnonymousUsage = true

[docker]
endpoint = "unix://var/run/docker.sock"
exposedByDefault = false

[api]
dashboard = true
entryPoint = "dashboard"

[entryPoints]
    [entryPoints.dashboard]
        address = ":8080"
        #[entryPoints.dashboard.auth.basic]
            #users = ["shamskhalil:$apr1$cqXqlUS7$CiSTm2T3B6GWOq/bFcKJ71"]
    [entryPoints.http]
        address = ":80"


