version: '3.7'
services:
  proxy:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    networks:
      - frontnet
    volumes:
      - /Users/shamskhalil/Desktop/nginx/proxy/lb.conf:/etc/nginx/conf.d/default.conf

  app1:
    image: node-balance:0.0.1
    restart: always
    networks:
      - frontnet

  app2:
    image: node-balance:0.0.1
    restart: always
    networks:
      - frontnet
    environment:
      - PORT=3001

  app3:
    image: node-balance:0.0.1
    restart: always
    networks:
      - frontnet
    environment:
      - PORT=3002

  app4:
    image: node-balance:0.0.1
    restart: always
    networks:
      - frontnet
    environment:
      - PORT=3003

networks:
  frontnet:


